// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhongKham.Infrastructure.Data;

namespace PhongKham.Infrastructure.Migrations
{
    [DbContext(typeof(PhongKhamDbContext))]
    [Migration("20230719093232_FixSomeIsuses")]
    partial class FixSomeIsuses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhongKham.Core.Entities.BacSi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenBacSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diaChiBS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sdtBS")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("bacSis");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.Benh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenBenh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("benhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.BenhNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenBenhNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dChiBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("sdtBN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("benhNhans");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ChiTietToaThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ThuocId")
                        .HasColumnType("int");

                    b.Property<int>("ToaThuocId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThuocId");

                    b.HasIndex("ToaThuocId");

                    b.ToTable("chiTietToaThuocs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<int>("PhieuKhamBenhId")
                        .HasColumnType("int");

                    b.Property<int>("ToaThuocId")
                        .HasColumnType("int");

                    b.Property<int>("TongThanhToan")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeHD")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("PhieuKhamBenhId");

                    b.HasIndex("ToaThuocId");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dChiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sdtNV")
                        .HasColumnType("int");

                    b.Property<string>("tenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuKhamBenh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BacSiId")
                        .HasColumnType("int");

                    b.Property<int?>("BenhId")
                        .HasColumnType("int");

                    b.Property<int?>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("TienKhamBenh")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeKhamBenh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("phieuKhamBenhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.Thuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cachDung")
                        .HasColumnType("int");

                    b.Property<int>("donVi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("thuocs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ToaThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhieuKhamBenhId")
                        .HasColumnType("int");

                    b.Property<int>("TongTienThuoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataTimeToaThuoc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamBenhId");

                    b.ToTable("toaThuocs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ChiTietToaThuoc", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongKham.Core.Entities.ToaThuoc", "ToaThuoc")
                        .WithMany("chiTietToaThuocs")
                        .HasForeignKey("ToaThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuoc");

                    b.Navigation("ToaThuoc");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.HoaDon", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.BenhNhan", "benhNhan")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongKham.Core.Entities.PhieuKhamBenh", "phieuKhamBenh")
                        .WithMany()
                        .HasForeignKey("PhieuKhamBenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongKham.Core.Entities.ToaThuoc", "toaThuoc")
                        .WithMany()
                        .HasForeignKey("ToaThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("benhNhan");

                    b.Navigation("phieuKhamBenh");

                    b.Navigation("toaThuoc");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuKhamBenh", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.BacSi", "bacSi")
                        .WithMany("phieuKhamBenhs")
                        .HasForeignKey("BacSiId");

                    b.HasOne("PhongKham.Core.Entities.Benh", "Benh")
                        .WithMany()
                        .HasForeignKey("BenhId");

                    b.HasOne("PhongKham.Core.Entities.BenhNhan", "benhNhan")
                        .WithMany("phieuKhamBenhs")
                        .HasForeignKey("BenhNhanId");

                    b.HasOne("PhongKham.Core.Entities.NhanVien", "nhanVien")
                        .WithMany("phieuKhamBenhs")
                        .HasForeignKey("NhanVienId");

                    b.Navigation("bacSi");

                    b.Navigation("Benh");

                    b.Navigation("benhNhan");

                    b.Navigation("nhanVien");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ToaThuoc", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.PhieuKhamBenh", "phieuKhamBenh")
                        .WithMany()
                        .HasForeignKey("PhieuKhamBenhId");

                    b.Navigation("phieuKhamBenh");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.BacSi", b =>
                {
                    b.Navigation("phieuKhamBenhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.BenhNhan", b =>
                {
                    b.Navigation("phieuKhamBenhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.NhanVien", b =>
                {
                    b.Navigation("phieuKhamBenhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ToaThuoc", b =>
                {
                    b.Navigation("chiTietToaThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
