// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhongKham.Infrastructure.Data;

namespace PhongKham.Infrastructure.Migrations
{
    [DbContext(typeof(PhongKhamDbContext))]
    [Migration("20230614082732_initPhongKhamDbContext")]
    partial class initPhongKhamDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhongKham.Core.Entities.BacSi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenBacSi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("bacSis");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.BenhNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenBenhNhan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("benhNhans");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ChiTietToaThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ThuocId")
                        .HasColumnType("int");

                    b.Property<int>("ToaThuocId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThuocId");

                    b.HasIndex("ToaThuocId");

                    b.ToTable("chiTietToaThuocs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.LichHen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<int>("DichVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeLichHen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("lichHens");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuKhamBenh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LichHenId")
                        .HasColumnType("int");

                    b.Property<string>("TenBenh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeKhamBenh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("LichHenId");

                    b.ToTable("phieuKhamBenhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuTiemPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LichHenId")
                        .HasColumnType("int");

                    b.Property<string>("TenTiemPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeTiemPhong")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LichHenId");

                    b.ToTable("phieuTiemPhongs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuTuVan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LichHenId")
                        .HasColumnType("int");

                    b.Property<string>("TenTuVan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeTuVan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LichHenId");

                    b.ToTable("phieuTuVans");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuXetNghiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LichHenId")
                        .HasColumnType("int");

                    b.Property<string>("TenXetNghiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTimeXetNghiem")
                        .HasColumnType("datetime2");

                    b.Property<int>("ketQuaXetNghiem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LichHenId");

                    b.ToTable("phieuXetNghiems");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.Thuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("TenThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("unitInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("thuocs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ToaThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhieuKhamBenhId")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<DateTime>("dataTimeToaThuoc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamBenhId")
                        .IsUnique();

                    b.ToTable("toaThuocs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ChiTietToaThuoc", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongKham.Core.Entities.ToaThuoc", "ToaThuoc")
                        .WithMany("chiTietToaThuocs")
                        .HasForeignKey("ToaThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuoc");

                    b.Navigation("ToaThuoc");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.LichHen", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.BenhNhan", null)
                        .WithMany("lichHens")
                        .HasForeignKey("BenhNhanId");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuKhamBenh", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.BacSi", "bacSi")
                        .WithMany("phieuKhamBenhs")
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhongKham.Core.Entities.LichHen", "lichHen")
                        .WithMany()
                        .HasForeignKey("LichHenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bacSi");

                    b.Navigation("lichHen");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuTiemPhong", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.LichHen", "lichHen")
                        .WithMany()
                        .HasForeignKey("LichHenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lichHen");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuTuVan", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.LichHen", "lichHen")
                        .WithMany()
                        .HasForeignKey("LichHenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lichHen");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuXetNghiem", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.LichHen", "lichHen")
                        .WithMany()
                        .HasForeignKey("LichHenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lichHen");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ToaThuoc", b =>
                {
                    b.HasOne("PhongKham.Core.Entities.PhieuKhamBenh", "phieuKhamBenh")
                        .WithOne("toaThuoc")
                        .HasForeignKey("PhongKham.Core.Entities.ToaThuoc", "PhieuKhamBenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("phieuKhamBenh");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.BacSi", b =>
                {
                    b.Navigation("phieuKhamBenhs");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.BenhNhan", b =>
                {
                    b.Navigation("lichHens");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.PhieuKhamBenh", b =>
                {
                    b.Navigation("toaThuoc");
                });

            modelBuilder.Entity("PhongKham.Core.Entities.ToaThuoc", b =>
                {
                    b.Navigation("chiTietToaThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
